"""

Revision ID: f16d103b0e83
Revises: 3aaa8f5da79a
Create Date: 2024-09-03 21:46:48.505105

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f16d103b0e83'
down_revision: Union[str, None] = '3aaa8f5da79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('user_oid', sa.Uuid(), nullable=False),
    sa.Column('friend_oid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('oid', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата обновления записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.ForeignKeyConstraint(['friend_oid'], ['user.oid'], ),
    sa.ForeignKeyConstraint(['user_oid'], ['user.oid'], ),
    sa.PrimaryKeyConstraint('oid'),
    sa.UniqueConstraint('oid')
    )
    op.alter_column('user', 'telegram_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['oid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'telegram_id',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.drop_table('friend')
    # ### end Alembic commands ###
