"""

Revision ID: 31f8ef7be9e0
Revises:
Create Date: 2024-09-29 22:18:53.585546

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31f8ef7be9e0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("telegram_id", sa.String(length=12), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("language_code", sa.String(length=8), nullable=True),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_user")),
        sa.UniqueConstraint("oid", name=op.f("uq_user_oid")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_user_telegram_id")),
    )
    op.create_table(
        "friend",
        sa.Column("user_oid", sa.Uuid(), nullable=False),
        sa.Column("friend_oid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["friend_oid"], ["user.oid"], name=op.f("fk_friend_friend_oid_user")
        ),
        sa.ForeignKeyConstraint(
            ["user_oid"], ["user.oid"], name=op.f("fk_friend_user_oid_user")
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_friend")),
        sa.UniqueConstraint("oid", name=op.f("uq_friend_oid")),
    )
    op.create_table(
        "shop_check",
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("creator_oid", sa.Uuid(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["creator_oid"], ["user.oid"], name=op.f("fk_shop_check_creator_oid_user")
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_shop_check")),
        sa.UniqueConstraint("oid", name=op.f("uq_shop_check_oid")),
    )
    op.create_table(
        "shop_check_item",
        sa.Column("shop_check_oid", sa.Uuid(), nullable=False),
        sa.Column("position_title", sa.String(length=128), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("count", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["shop_check_oid"],
            ["shop_check.oid"],
            name=op.f("fk_shop_check_item_shop_check_oid_shop_check"),
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_shop_check_item")),
        sa.UniqueConstraint("oid", name=op.f("uq_shop_check_item_oid")),
    )
    op.create_table(
        "shop_check_item_split",
        sa.Column("shop_check_item_oid", sa.Uuid(), nullable=False),
        sa.Column("user_oid", sa.Uuid(), nullable=False),
        sa.Column("share", sa.Integer(), nullable=False),
        sa.Column("oid", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["shop_check_item_oid"],
            ["shop_check_item.oid"],
            name=op.f("fk_shop_check_item_split_shop_check_item_oid_shop_check_item"),
        ),
        sa.ForeignKeyConstraint(
            ["user_oid"],
            ["user.oid"],
            name=op.f("fk_shop_check_item_split_user_oid_user"),
        ),
        sa.PrimaryKeyConstraint("oid", name=op.f("pk_shop_check_item_split")),
        sa.UniqueConstraint("oid", name=op.f("uq_shop_check_item_split_oid")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_check_item_split")
    op.drop_table("shop_check_item")
    op.drop_table("shop_check")
    op.drop_table("friend")
    op.drop_table("user")
    # ### end Alembic commands ###
